version: "3"
networks:
  cluster_net:
    external:
      name: cassandra_net

  cassandra:
    image: cassandra:3.11
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
      replicas: 1
    entrypoint:
    - "sh"
    - "-c"
    - export CASSANDRA_SEEDS=$$(nrOfTasks=`getent hosts tasks.cassandra | wc -l` ;
      many=`getent hosts tasks.cassandra | awk '{print $$1}' | sed "/$$(hostname --ip-address)/d"
      | paste -d, -s -` ; printf '%s' $$( [ $${nrOfTasks} -gt 1 ] && echo $${many} ||
      echo "$$(hostname --ip-address)" )) ; /docker-entrypoint.sh cassandra -f
    volumes:
        - /mnt/cassandra:/var/lib/cassandra 
    networks:
      - cluster_net